let
    Source = Folder.Files("C:\Users\Peter\Desktop\PBI Data Jobs"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"Job Title", type text}, {"Salary Estimate", type text}, {"Job Description", type text}, {"Rating", type number}, {"Company Name", type text}, {"Location", type text}, {"Headquarters", type text}, {"Size", type text}, {"Founded", Int64.Type}, {"Type of ownership", type text}, {"Industry", type text}, {"Sector", type text}, {"Revenue", type text}, {"Competitors", type text}, {"Easy Apply", type text}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Source.Name", "Source.Name - Copy"),
    #"Reordered Columns" = Table.ReorderColumns(#"Duplicated Column",{"Source.Name", "Source.Name - Copy", "Job Title", "Salary Estimate", "Job Description", "Rating", "Company Name", "Location", "Headquarters", "Size", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors", "Easy Apply"}),
    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns",".csv","",Replacer.ReplaceText,{"Source.Name - Copy"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","BusinessAnalyst","Business Analyst",Replacer.ReplaceText,{"Source.Name - Copy"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","DataAnalyst","Data Analyst",Replacer.ReplaceText,{"Source.Name - Copy"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","DataScientist","Data Scientist",Replacer.ReplaceText,{"Source.Name - Copy"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","DataEngineer","Data Engineer",Replacer.ReplaceText,{"Source.Name - Copy"}),
    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value4",{"Job Title", "Source.Name"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Source.Name - Copy", "Job Title"}}),
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Salary Estimate] <> "$10-$26 Per Hour(Glassdoor est.)" and [Salary Estimate] <> "$17-$27 Per Hour(Glassdoor est.)" and [Salary Estimate] <> "$34-$53 Per Hour(Glassdoor est.)" and [Salary Estimate] <> "-1")),
    #"Replaced Value5" = Table.ReplaceValue(#"Filtered Rows","$","",Replacer.ReplaceText,{"Salary Estimate"}),
    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value5", each true),
    #"Replaced Value6" = Table.ReplaceValue(#"Filtered Rows1","K","",Replacer.ReplaceText,{"Salary Estimate"}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Replaced Value6", "Salary Estimate", Splitter.SplitTextByEachDelimiter({"("}, QuoteStyle.Csv, false), {"Salary Estimate.1", "Salary Estimate.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Salary Estimate.1", type text}, {"Salary Estimate.2", type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"Salary Estimate.2"}),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Removed Columns1", "Salary Estimate.1", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, false), {"Salary Estimate.1.1", "Salary Estimate.1.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Salary Estimate.1.1", Int64.Type}, {"Salary Estimate.1.2", Int64.Type}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type2", "Salary", each (([Salary Estimate.1.1] + [Salary Estimate.1.2]) / 2 ) * 1000),
    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom",{"Job Title", "Salary Estimate.1.1", "Salary Estimate.1.2", "Salary", "Job Description", "Rating", "Company Name", "Location", "Headquarters", "Size", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors", "Easy Apply"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns1",{"Salary Estimate.1.1", "Salary Estimate.1.2"}),
    #"Added Custom1" = Table.AddColumn(#"Removed Columns2", "Company", each Text.Remove(
        [Company Name],
        {"0".."9"}
        )),
    #"Replaced Value7" = Table.ReplaceValue(#"Added Custom1",".","",Replacer.ReplaceText,{"Company"}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Replaced Value7",{"Job Title", "Salary", "Job Description", "Rating", "Company Name", "Company", "Location", "Headquarters", "Size", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors", "Easy Apply"}),
    #"Removed Columns3" = Table.RemoveColumns(#"Reordered Columns2",{"Company Name"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns3",{{"Company", "Company Name"}}),
    #"Filtered Rows2" = Table.SelectRows(#"Renamed Columns2", each ([Size] <> "-1" and [Size] <> "Unknown")),
    #"Replaced Value8" = Table.ReplaceValue(#"Filtered Rows2","employees","",Replacer.ReplaceText,{"Size"}),
    #"Split Column by Delimiter2" = Table.SplitColumn(#"Replaced Value8", "Size", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Size.1", "Size.2"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"Size.1", Int64.Type}, {"Size.2", type text}}),
    #"Replaced Value9" = Table.ReplaceValue(#"Changed Type3","to","",Replacer.ReplaceText,{"Size.2"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","","10000",Replacer.ReplaceValue,{"Size.2"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value10",{{"Size.2", Int64.Type}}),
    #"Added Custom2" = Table.AddColumn(#"Changed Type4", "Company Size", each ([Size.1] + [Size.2]) / 2),
    #"Reordered Columns3" = Table.ReorderColumns(#"Added Custom2",{"Job Title", "Salary", "Job Description", "Rating", "Company Name", "Location", "Headquarters", "Size.1", "Size.2", "Company Size", "Founded", "Type of ownership", "Industry", "Sector", "Revenue", "Competitors", "Easy Apply"}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Reordered Columns3",{{"Company Size", Int64.Type}}),
    #"Removed Columns4" = Table.RemoveColumns(#"Changed Type5",{"Size.1", "Size.2"}),
    #"Filtered Rows3" = Table.SelectRows(#"Removed Columns4", each true),
    #"Removed Columns5" = Table.RemoveColumns(#"Filtered Rows3",{"Competitors"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Removed Columns5","-1","0",Replacer.ReplaceText,{"Easy Apply"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","TRUE","1",Replacer.ReplaceText,{"Easy Apply"}),
    #"Filtered Rows4" = Table.SelectRows(#"Replaced Value12", each ([Sector] <> "-1") and ([Industry] <> "-1") and ([Founded] <> -1)),
    #"Filtered Rows5" = Table.SelectRows(#"Filtered Rows4", each ([Rating] <> -1)),
    #"Replaced Value13" = Table.ReplaceValue(#"Filtered Rows5","-1","",Replacer.ReplaceText,{"Job Description"}),
    #"Filtered Rows6" = Table.SelectRows(#"Replaced Value13", each true),
    #"Changed Type6" = Table.TransformColumnTypes(#"Filtered Rows6",{{"Salary", Int64.Type}}),
    #"Filtered Rows7" = Table.SelectRows(#"Changed Type6", each true),
    #"Split Column by Delimiter3" = Table.SplitColumn(#"Filtered Rows7", "Location", Splitter.SplitTextByEachDelimiter({", "}, QuoteStyle.Csv, false), {"Location.1", "Location.2"}),
    #"Changed Type7" = Table.TransformColumnTypes(#"Split Column by Delimiter3",{{"Location.1", type text}, {"Location.2", type text}}),
    #"Renamed Columns3" = Table.RenameColumns(#"Changed Type7",{{"Location.1", "City"}, {"Location.2", "State"}}),
    #"Filtered Rows8" = Table.SelectRows(#"Renamed Columns3", each true)
in
    #"Filtered Rows8"
